"""UI-specific checks for the premium redesign."""
import sys
from database import init_db; init_db()
import app as flask_app
c = flask_app.app.test_client()

PASS = []; FAIL = []
def check(label, cond, detail=''):
    if cond: PASS.append(label); print(f'  OK  {label}')
    else: FAIL.append(label); print(f'  FAIL {label}  {detail}')

def html(route):
    return c.get(route).data.decode()

# ── base.html ────────────────────────────────────────────────────────────────
print('\n=== BASE.HTML ===')
h = html('/')
check('Inter font loaded',            'fonts.googleapis.com' in h)
check('SVG P-pin logo present',       'viewBox="0 0 34 38"' in h)
check('brand-name SmartPark',         'SmartPark' in h)
check('brand-tagline present',        'Slot Allocator' in h)
check('status-dot element present',   'status-dot' in h)
check('System Online text',           'System Online' in h)
check('No emoji in navbar brand',     '🅿️' not in h and '🚗' not in h)
check('Nav SVG icons present',        'nav-icon' in h)
check('Dashboard nav link',           'href="/"' in h)
check('Parking Lot nav link',         'href="/parking"' in h)
check('History nav link',             'href="/history"' in h)
check('Algorithms nav link',          'href="/algorithms"' in h)
check('toast-container present',      'id="toast-container"' in h)
check('main.js loaded',               'main.js' in h)

# ── index.html ───────────────────────────────────────────────────────────────
print('\n=== INDEX.HTML (dashboard) ===')
h = html('/')
check('dashboard-hero present',       'dashboard-hero' in h)
check('hero SmartPark heading',       '>Smart<span>Park</span>' in h or 'Smart<span>Park</span>' in h)
check('hero-subtitle present',        'hero-subtitle' in h)
check('stat-total card',              'id="stat-total"' in h)
check('stat-available card',          'id="stat-available"' in h)
check('stat-occupied card',           'id="stat-occupied"' in h)
check('stat-reserved card',           'id="stat-reserved"' in h)
check('stat-today card',              'id="stat-today"' in h)
check('stat-avg-time card',           'id="stat-avg-time"' in h)
check('utilization bar present',      'id="utilization-bar"' in h)
check('stat-utilization label',       'id="stat-utilization"' in h)
check('vehicles-list present',        'id="vehicles-list"' in h)
check('Smart Insights section',       'Smart Insights' in h)
check('ins-util insight',             'id="ins-util"' in h)
check('ins-ev insight',               'id="ins-ev"' in h)
check('Algo reference cards',         'Greedy Algorithm' in h and 'Priority Queue' in h and 'Binary Search' in h)
check('Correct PQ complexity shown',  'O(n log n)' in h)
check('Correct BS complexity shown',  'O(log n)' in h and 'O(n log n)' in h)
check('exit-modal present',           'id="exit-modal"' in h)
check('exit-vehicle-no input',        'id="exit-vehicle-no"' in h)
check('parking.js loaded on index',   'parking.js' in h)
check('No bare emoji chars',          '🅿️' not in h and '🏍️' not in h)

# ── parking.html ─────────────────────────────────────────────────────────────
print('\n=== PARKING.HTML ===')
h = html('/parking')
check('parking-lot-wrapper present',  'id="parking-lot-wrapper"' in h)
check('row-A,B,C,D divs present',     'id="row-A"' in h and 'id="row-D"' in h)
check('car-layer present',            'id="car-layer"' in h)
check('slot-detail-panel present',    'id="slot-detail-panel"' in h)
check('slot-action-area present',     'id="slot-action-area"' in h)
check('viz-steps present',            'id="viz-steps"' in h)
check('bs-steps-panel present',       'id="bs-steps-panel"' in h)
check('vehicles-list present',        'id="vehicles-list"' in h)
check('park-modal present',           'id="park-modal"' in h)
check('vehicle-no input',             'id="vehicle-no"' in h)
check('vehicle-type select',          'id="vehicle-type"' in h)
check('priority select',              'id="priority"' in h)
check('park-mode radios',             'name="park-mode"' in h)
check('pm-smart-panel',               'id="pm-smart-panel"' in h)
check('pm-manual-panel',              'id="pm-manual-panel"' in h)
check('find-slot-btn',                'id="find-slot-btn"' in h)
check('alloc-result div',             'id="alloc-result"' in h)
check('confirm-park-btn',             'id="confirm-park-btn"' in h)
check('manual-selected-display',      'id="manual-selected-display"' in h)
check('manual-slot-badge',            'id="manual-slot-badge"' in h)
check('bs-explain-box',               'id="bs-explain-box"' in h)
check('confirm-manual-btn',           'id="confirm-manual-btn"' in h)
check('map-selector-modal z-index',   'z-index:300' in h)
check('map-selector-lot',             'id="map-selector-lot"' in h)
check('map-sel-confirm-btn',          'id="map-sel-confirm-btn"' in h)
check('exit-quick-modal',             'id="exit-quick-modal"' in h)
check('exit-vehicle-no input',        'id="exit-vehicle-no"' in h)
check('floor-selector present',       'id="floor-selector"' in h)
check('floor-stats-bar present',      'class="floor-stats-bar"' in h)
check('preferred-area removed',       'id="preferred-area"' not in h)
check('lot-and-panel present',        'lot-and-panel' in h)
check('parking.js loaded',            'parking.js' in h)

# ── algorithms.html ──────────────────────────────────────────────────────────
print('\n=== ALGORITHMS.HTML ===')
h = html('/algorithms')
check('Greedy section present',       'Greedy Algorithm' in h)
check('PQ section present',           'Priority Queue' in h)
check('BS section present',           'Binary Search' in h)
check('PQ build O(n log n) correct',  'O(n log n)' in h)
check('BS search O(log n) correct',   'O(log n)' in h)
check('heapq reference present',      'heapq' in h or 'heappush' in h)
check('Pre-sort note present',        'preprocessing' in h or 'pre' in h.lower())
check('demo-type select',             'id="demo-type"' in h)
check('demo-priority select',         'id="demo-priority"' in h)
check('demo-search input',            'id="demo-search"' in h)
check('run-demo-btn',                 'id="run-demo-btn"' in h)
check('viz-steps-main present',       'id="viz-steps-main"' in h)
check('pq-output present',            'id="pq-output"' in h)
check('pq-steps-log present',         'id="pq-steps-log"' in h)
check('greedy-output present',        'id="greedy-output"' in h)
check('greedy-steps-log present',     'id="greedy-steps-log"' in h)
check('bs-result-box present',        'id="bs-result-box"' in h)
check('bs-steps-log present',         'id="bs-steps-log"' in h)
check('No emoji chars',               '🧮' not in h and '🔵' not in h)

# ── history.html ─────────────────────────────────────────────────────────────
print('\n=== HISTORY.HTML ===')
h = html('/history')
check('hist-total present',           'id="hist-total"' in h)
check('hist-exited present',          'id="hist-exited"' in h)
check('hist-active present',          'id="hist-active"' in h)
check('hist-avg present',             'id="hist-avg"' in h)
check('Filter tabs present',          'filter-tab' in h)
check('Filter: All tab',              '>All<' in h)
check('Filter: Active tab',           '>Active<' in h)
check('Filter: Completed tab',        '>Completed<' in h)
check('search-input present',         'id="search-input"' in h)
check('history-table present',        'id="history-table"' in h)
check('history-body present',         'id="history-body"' in h)
check('Algorithm column present',     'Algorithm' in h)
check('No emoji chars',               '📋' not in h and '✅' not in h)

# ── CSS checks ───────────────────────────────────────────────────────────────
print('\n=== STYLE.CSS ===')
r = c.get('/static/css/style.css')
css = r.data.decode()
check('CSS loads (200)',              r.status_code == 200)
check('--bg-primary token',           '--bg-primary' in css)
check('--cyan token',                 '--cyan' in css)
check('.parking-slot class',          '.parking-slot' in css)
check('.parking-slot.available',      '.parking-slot.available' in css)
check('.parking-slot.occupied',       '.parking-slot.occupied' in css)
check('.parking-slot.selected',       '.parking-slot.selected' in css)
check('.modal-backdrop class',        '.modal-backdrop' in css)
check('.modal-backdrop.show',         '.modal-backdrop.show' in css)
check('.stat-card present',           '.stat-card' in css)
check('.btn classes present',         '.btn-primary' in css and '.btn-danger' in css)
check('.badge classes present',       '.badge-green' in css and '.badge-red' in css)
check('.viz-step present',            '.viz-step' in css)
check('.algo-steps present',          '.algo-steps' in css)
check('.pq-table present',            '.pq-table' in css)
check('.vehicle-card present',        '.vehicle-card' in css)
check('.floor-stats-bar present',     '.floor-stats-bar' in css)
check('.lot-and-panel present',       '.lot-and-panel' in css)
check('.parking-lot-wrapper',         '.parking-lot-wrapper' in css)
check('.parking-row present',         '.parking-row' in css)
check('.recommendation-box',          '.recommendation-box' in css)
check('.result-slot-card',            '.result-slot-card' in css)
check('.mode-option present',         '.mode-option' in css)
check('.algo-flow-box present',       '.algo-flow-box' in css)
check('.dashboard-hero present',      '.dashboard-hero' in css)
check('.filter-tabs present',         '.filter-tabs' in css)
check('.insights-grid present',       '.insights-grid' in css)
check('.algo-card present',           '.algo-card' in css)
check('.complexity-block present',    '.complexity-block' in css)
check('min-height on lot wrapper',    'min-height: 600px' in css or 'min-height:600px' in css)
check('lot-and-panel grid columns',   'minmax(560px' in css)

# ── main.js checks ───────────────────────────────────────────────────────────
print('\n=== MAIN.JS ===')
r2 = c.get('/static/js/main.js')
js = r2.data.decode()
check('main.js loads (200)',          r2.status_code == 200)
check('API.get defined',              'async get(url)' in js)
check('API.post defined',             'async post(url' in js)
check('showToast defined',            'function showToast' in js)
check('openModal defined',            'function openModal' in js)
check('closeModal defined',           'function closeModal' in js)
check('refreshStats defined',         'async function refreshStats' in js)
check('vehicleIcon SVG (no emoji)',   'function vehicleIcon' in js and 'svg' in js.lower())
check('vehicleIcon no emoji chars',   '🚗' not in js and '🏍️' not in js)
check('priorityLabel defined',        'function priorityLabel' in js)
check('formatDuration defined',       'function formatDuration' in js)
check('formatTime defined',           'function formatTime' in js)
check('setActiveNav defined',         'function setActiveNav' in js)
check('animateCount defined',         'function animateCount' in js)
check('map-selector-modal excluded',  'map-selector-modal' in js)

# ── Summary ──────────────────────────────────────────────────────────────────
print(f'\n{"="*52}')
print(f'PASSED: {len(PASS)}/{len(PASS)+len(FAIL)}')
if FAIL:
    print(f'FAILED: {len(FAIL)}')
    for f in FAIL: print(f'  - {f}')
    sys.exit(1)
else:
    print('ALL UI TESTS PASSED')
